env:
  node: true
  es6:  true
parserOptions:
  ecmaVersion: 2020
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off # enforcing of linebreaks is done through .gitattributes
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-use-before-define: error
  no-array-constructor: error
  prefer-const: error
  no-var: error
